AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CloudFormation BIL INVOICE RDS
Resources:
#RDS CLUSTER
  RDSCLUSTER:
    Type: AWS::RDS::DBCluster
    Properties:
      AvailabilityZones:
      - eu-west-1c
      - eu-west-1d
      - eu-west-1a
      BackupRetentionPeriod: 1
      CopyTagsToSnapshot: true
      DBClusterIdentifier: bil-microservices-demo
  #     # DBClusterParameterGroup: default.mariadb-10.6.7
      # DatabaseName: invoice-extraction
      DeletionProtection: true
      Engine: aurora
  #     EngineMode: provisioned
      EngineVersion: 5.7.mysql_aurora.2.07.2
  #     # HttpEndpointEnabled: false
  #     KmsKeyId: !Ref KMS
  #     MasterUsername: admin
  #     MasterUserPassword: admin
      Port: 3306
      PreferredBackupWindow: 03:42-04:12
      PreferredMaintenanceWindow: thu:22:34-thu:23:04
      SnapshotIdentifier: "arn:aws:rds:eu-west-1:871157674040:cluster-snapshot:snapshot-for-cloudformation"
      StorageEncrypted: true
      # VpcSecurityGroupIds:
      #  - sg-0ece504dc54905150
