AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CloudFormation BIL INVOICE RDS
Resources:

#KMS Key
  KMS:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action:
              - 'kms:*'
            Resource: 
              - '*'
DBClusters:
  Type: AWS::RDS::DBCluster
  Properties:
    AvailabilityZones:
    - eu-west-1c
    - eu-west-1b
    - eu-west-1a
    BackupRetentionPeriod: 1
    CopyTagsToSnapshot: true
    DBClusterIdentifier: bil-microservices-aurora-demo
    DBClusterParameterGroupName: aurora-mysql57-ssl-required
    # DBSubnetGroupName: bil_microservices-rds-subnet-group
    DatabaseName: invoiceai_dev
    DeletionProtection: true
    Engine: aurora-mysql
    EngineMode: provisioned
    EngineVersion: 5.7.mysql_aurora.2.07.2
    KmsKeyId: !Ref KMS
    MasterUsername: admin
    MasterUserPassword: invoiceadmin
    Port: 3306
    PreferredBackupWindow: 03:42-04:12
    PreferredMaintenanceWindow: thu:22:34-thu:23:04
    StorageEncrypted: true
    VpcSecurityGroupIds: 
    - sg-0ece504dc54905150