AWSTemplateFormatVersion: 2010-09-09
Description: BIL Cloudformation
Resources:
  ALB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        IpAddressType: ipv4
        LoadBalancerAttributes: 
        - Key: access_logs.s3.enabled
          Value: 'true'
        - Key: access_logs.s3.bucket
          Value: bil-loadbalancer-logs
        - Key: idle_timeout.timeout_seconds
          Value: '1320'
        - Key: deletion_protection.enabled
          Value: 'false'
        - Key: routing.http2.enabled
          Value: 'true'
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: 'false'
        - Key: routing.http.xff_client_port.enabled
          Value: 'false'
        - Key: routing.http.desync_mitigation_mode
          Value: defensive
        - Key: waf.fail_open.enabled
          Value: 'false'
        - Key: routing.http.x_amzn_tls_version_and_cipher_suite.enabled
          Value: 'false'
        Name: bil-microservices-elb-01-demo
        Scheme: internet-facing
        SecurityGroups: 
          - sg-012c31dbd3d1f9c6b
        Subnets: 
          - subnet-059d49d62da5ac1cf
          - subnet-0cee8c1d17cecfce5
        Type: application

#aws elbv2 describe-load-balancer-attributes --load-balancer-arn arn:aws:elasticloadbalancing:eu-west-1:871157674040:loadbalancer/app/bil-microservices-elb-01/7c56c7ed89b1d129