# aws lambda get-function --function-name  integration-invoice_extraction
# aws iam get-role --role-name integration-invoice_extraction-role-1uxitxb8
AWSTemplateFormatVersion: 2010-09-09
Description: BIL Lambda
Resources:
#LAMBDA POLICY Lambda-Basic-Execution-Role
  LambdaPolicy1:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: 'AWS Lambda Basic ExecutionRole'
      ManagedPolicyName: Lambda-Basic-Execution-Role-Demo
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 'logs:CreateLogGroup'
            Resource: 'arn:aws:logs:eu-west-1:871157674040:*'
          - Effect: Allow
            Action: 
             - 'logs:CreateLogStream'
             - 'logs:PutLogEvents'
            Resource: 'arn:aws:logs:eu-west-1:871157674040:log-group:/aws/lambda/integration-invoice_extraction:*'
#LAMBDA POLICY Lambda-VPC-Access-Execution-Role
  LambdaPolicy2:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: 'AWS Lambda VPC Access Execution Role'
      ManagedPolicyName: Lambda-VPC-Access-Execution-Role-Demo
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 
             - 'ec2:CreateNetworkInterface'
             - 'ec2:DeleteNetworkInterface'
             - 'ec2:DescribeNetworkInterfaces'
            Resource: '*'
#LAMBDA POLICY BIL-LAMBDA-DEVELOPER
  LambdaPolicy3:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: 'AWS Lambda Developer'
      ManagedPolicyName: BIL-LAMBDA-DEVELOPER-DEMO
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Sid: 'VisualEditor0'
            Action: 
             - 'elasticloadbalancing:DescribeLoadBalancers'
             - 'codedeploy:PutLifecycleEventHookExecutionStatus'
             - 'elasticloadbalancing:DescribeListeners'
             - 'ssm:DescribeParameters'
             - 'serverlessrepo:SearchApplications'
            Resource: '*'
          - Effect: Allow
            Sid: 'VisualEditor1'
            Action: ['codedeploy:GetDeployment', 'ssm:GetParameter']
            Resource: 
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/DEV.INVOICE_EXTRACTION*"
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/TEST.INVOICE_EXTRACTION*"
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/PROD.INVOICE_EXTRACTION*"
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/DEV.COGNITIVE_FAQ*"
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/TEST.COGNITIVE_FAQ*"
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/PROD.COGNITIVE_FAQ*"
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/DEV.GEODATA*"
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/TEST.GEODATA*"
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/PROD.GEODATA*"
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/DEV.ENTITY_MANAGER*"
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/TEST.ENTITY_MANAGER*"
              - "arn:aws:ssm:eu-west-1:871157674040:parameter/PROD.ENTITY_MANAGER*"
              - "arn:aws:codedeploy:*:871157674040:deploymentgroup:*/*"
#LAMBDA ROLE
  LambdaRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: integration-invoice_extraction-role
      ManagedPolicyArns: 
        - !Ref LambdaPolicy1
        - !Ref LambdaPolicy2
        - !Ref LambdaPolicy3
      RoleName: integration-invoice_extraction-role-demo

#LAMBDA FUNCTION
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: invoice-extraction-eu-demo
        S3Key: integration-invoice_extraction.zip
      Architectures: 
       - 'x86_64'
      Description: 'Invoice Extraction Integreation Lambda Function'
      Environment:
        Variables:
          REGION_NAME: eu-west-1
      EphemeralStorage:
        Size: 512
      FunctionName: integration-invoice_extraction-demo
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      PackageType: Zip
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: python3.8
      Timeout: 320
      TracingConfig:
        Mode: PassThrough
      VpcConfig:
        SecurityGroupIds:
        - sg-081d4dd051a86ae31
        SubnetIds:
        - subnet-05677243c8da07bf5
        - subnet-0e87cfbd496675012
